---
title: Policy Paper
---



----

## Neues zur Lohnungleichheit in Deutschland



<a href="https://www.ifo.de/publikationen/2020/aufsatz-zeitschrift/ungleichheit-unter-der-lupe-neue-politische-antworten-auf"> Article  </a> 

“Neues zur Lohnungleichheit in Deutschland” (2020, with __Mario Bossler__ and __Bernd Fitzenberger__),<br> _ifo-Schnelldienst 02/2020_ 

Die Lohnungleichheit unter Vollzeitbeschäftigten in
Westdeutschland ist zwischen 1990 und 2010 stark
angestiegen, wobei die Reallöhne im unteren Bereich
der Lohnverteilung deutlich gefallen sind. Neuere
Befunde zeigen, dass neben anderen in der Literatur
diskutierten Faktoren die zunehmende Heterogenität der Erwerbsverläufe einen Teil des Anstiegs der
Lohnungleichheit erklären kann. Seit 2011 ist dahingehend eine Trendwende zu erkennen, dass die Löhne
der Vollzeitbeschäftigten in Westdeutschland entlang
der gesamten Lohnverteilung gestiegen sind und die
Lohnungleichheit nicht mehr weiter zugenommen
hat. Mit der Einführung des gesetzlichen Mindestlohns
im Jahr 2015 erhöht sich das 10%-Quantil der gesamtdeutschen Lohnverteilung, was mit einem Rückgang
der Lohnungleichheit am unteren Ende der Lohnverteilung – vor allem in Ostdeutschland – einhergeht.


